### ISSUE TITLE
Addition to plugin :D

### ISSUE THREAD

**Issue by nscwalk** [mrlolethan/NexGen-KoTHs#1]
It would be great if a person would receive 1 credit when they win a koth. And you can set the koth chest the loot table and it will take 1 credit to open the koth chest with the random amount of loot

**Comment by EthanJoyce** [comment]
This project has practically been "abandoned." I've started work on a complete rewrite of the plugin, so this could possibly be in that.

**Comment by EthanJoyce** [comment]
Thanks for the suggestion!

**Comment by YouShallNevaKnow** [comment]
how much further is this rewrite?
